const responseCodeConstant = {
	"SUCCESS": 200,
	"MISSING_HEADERS": 100,
	"INVALID_DIVICE_TYPE": 101,
	"INVALID_API_KEY": 102,
	"ACCESS_TOKEN_REQUIRED": 103,
	"INVALID_TOKEN": 104,
	"VALIDATION_ERROR": 105,
	"UNAUTHORIZED_ACCESS": 106,
	"INVALID_LOGIN_CREDENTIALS": 111,
	"EMAIL_EXIST": 112,
	"TOKEN_EXPIRE": 113,
	"SALON_CODE_VALID": 114,
	"INVALID_SALON_CODE": 115,
	"SALON_CODE_REQUIRED": 116,
	"SALON_CNF_TOKEN_REQUIRED": 117,
	"SALON_CNF_TOKEN_SENT": 118
}
export default responseCodeConstant;